name: Deploy to Debian (Apache, orditrack)

on:
  push:
    branches: [ "main" ]   # change si besoin
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- PHP/Composer (optionnel) ---
      - name: Install PHP deps (Composer)
        if: hashFiles('composer.json') != ''
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli unzip
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          composer install --no-dev --optimize-autoloader

      # --- Node (optionnel) ---
      - name: Setup Node
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: NPM CI & Build
        if: hashFiles('package.json') != ''
        run: |
          npm ci
          npm run build || true
          # npm run export || true  # si site statique

      # --- SSH ---
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan "$DEPLOY_HOST" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}

      # --- Déploiement (rsync) ---
      - name: Rsync to server
        run: |
          rsync -az --delete \
            --exclude=".git" \
            --exclude=".github" \
            --exclude="node_modules" \
            -e ssh \
            ./ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

      # --- Permissions & reload Apache ---
      - name: Fix perms & reload Apache
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST '
            find $DEPLOY_PATH -type d -exec chmod 2775 {} \; &&
            find $DEPLOY_PATH -type f -exec chmod 664 {} \; &&
            sudo systemctl reload apache2 || true
          '
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
