name: Deploy to Debian (Apache, orditrack)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- PHP/Composer (optionnel) ---
      - name: Install PHP deps (Composer)
        if: hashFiles('composer.json') != ''
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli unzip
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          composer install --no-dev --optimize-autoloader

      # --- Node (optionnel) ---
      - name: Setup Node
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: NPM CI & Build
        if: hashFiles('package.json') != ''
        run: |
          npm ci
          npm run build || true

      # --- SSH ---
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          cat > ~/.ssh/id_ed25519 << 'EOF'
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACC0O6Ms9tkcTLFxtKQz/R+oPHBtQPvXSnajiUNOEw4TPgAAAJCE3cQVhN3E
FQAAAAtzc2gtZWQyNTUxOQAAACC0O6Ms9tkcTLFxtKQz/R+oPHBtQPvXSnajiUNOEw4TPg
AAAEA6x83a48rmwPWPTaEgp7QhLU0fOHrcQLDKwS+rPoYIErQ7oyz22RxMsXG0pDP9H6g8
cG1A+9dKdqOJQ04TDhM+AAAACmdoYS1kZXBsb3kBAgM=
-----END OPENSSH PRIVATE KEY-----
EOF
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan 172.16.160.159 >> ~/.ssh/known_hosts

      # --- Déploiement (rsync) ---
      - name: Rsync to server
        run: |
          rsync -az --delete \
            --exclude=".git" \
            --exclude=".github" \
            --exclude="node_modules" \
            --exclude="*.log" \
            -e ssh \
            ./ deploy@172.16.160.159:/var/www/html/orditrack/

      # --- Permissions & reload Apache ---
      - name: Fix perms & reload Apache
        run: |
          ssh deploy@172.16.160.159 '
            find /var/www/html/orditrack -type d -exec chmod 2775 {} \; &&
            find /var/www/html/orditrack -type f -exec chmod 664 {} \; &&
            sudo systemctl reload apache2 || true
          '
